### ISSUE TITLE
Is it possible to search for at least one keyword?

### ISSUE THREAD

**Issue by vsund** [edavis/hnrss#12]
I wonder whether it's possible to search for `foo` or `bar` and not how it's default for `foo` and `bar`.

Of course it's possible to use two feeds and let the feed reader filter out, but it would be cooler to have this directly in the feed :)

**Comment by edavis** [comment]
Hey @vsund — This should be good to go. `?q=Term1 OR Term2` would work as expected now.

For example: http://hnrss.org/newest?q=WordPress+OR+Django (titles contain either WordPress or Django).

Let me know if this is working for you. Thanks!

**Comment by vsund** [comment]
Sorry, forgot to answer here :)

This works for some keyword pairs but though I found something confusing: https://hnrss.org/newest?q=git+OR+linux gives me results that don't contain a keyword. If I'm right, it should look only at the title by default. How does these results come in?

**Comment by edavis** [comment]
Hey @vsund — Interesting. Can reproduce. Good catch.

Looks like I might have to work on surrounding each term with quotes, as doing that manually seems to work as expected: https://hnrss.org/newest?q=%22git%22%20OR%20%22linux%22

Algolia (the results provider) probably uses a different search mode when query terms are surrounded by quotes vs. when they're not. Without the quotes, I do see a handful of "get" and "got" in the titles, so maybe it thinks "git" is a misspelling and tries to be "helpful."

Anyway, re-opening to keep this on my radar. Thanks.

**Comment by QuinnyPig** [comment]
As a followup, adding multiple quoted terms to the keyword section breaks the RSS validation scheme; apparently the backslash in `</atom>` breaks the standard?

**Comment by edavis** [comment]
@QuinnyPig Good catch. Should be fixable with some URL quoting. I'll dig into this today.

**Comment by edavis** [comment]
@vsund @QuinnyPig Search feeds with multiple terms should be handled better now: https://hnrss.org/newest?q=git%20OR%20linux

- No longer need to quote each term, the app will do the right thing and return relevant results. That said, any queries that do contain quotes (e.g., `q="git" OR "linux"`) are still handled; they're just passed through unchanged.

- The `atom:link` element is properly escaped (`'"' -> %22, ' ' -> %20`) so the feeds properly validate.

I've thrown every combination I can think of at it and all seems fine, but feel free to re-open if I missed something!
