### ISSUE TITLE
Make hnrss available for external access?

### ISSUE THREAD

**Issue by srissel** [edavis/hnrss#19]
Hello,

Thanks for your implementation, it really looks great!
I know this is more a general Linux/Apache question, but since I'm not that deep into Linux, I dare to ask....

I have setup hnrss on my Linux web server, it's running but only with internal access via 127.0.0.1.
I'd like to make the service available for external access, to integrate it into 3rd party news aggregators like Flipboard.

Do you have any instructions at hand, how to do this?
(I'd like to do this with my own installation of hnrss, in order to be able to increase the hard coded maximum of items to retrieve from the default 100 to a greater number)

I tried setting a IPTable rule to map external port 5000 to internal port 5000, but that did not work.

Any help is welcome!
Thanks in advance.

Sascha.

**Comment by edavis** [comment]
Hi Sascha — I'd recommend you buy a cheap VPS plan from a provider like DigitalOcean, Rackspace, Linode, etc. and host your local copy of hnrss there. With enough time and energy you _might_ be able to host it on your local machine in a way that external services can find it, but it'll be a real hassle to get there.

Running it on a VPS won't be much different than how you're running it now, it'll just be much easier for the "outside world" to access it.

Hope this helps!

**Comment by srissel** [comment]
Thanks for your answer,

I've already a VPS running, with apache and some other services working fine.

I am just wondering, which is the best way to get your python implementation running.
I found sites, describing how to integrate python executed as CGI scripts into apache. I think this would allow your scripts to be run by external requests.

But on the other hand: Your implementation is launching its own web server running on 127.0.0.1:5000. So why integrate it into apache?
Isn't the easiest way mapping the internal server on 127.0.0.1:5000 to some external port?
As described above, an IPTables entry didn't work.
Maybe I missed something. Therefore my question here...

If you can't help - thanks anyway!

**Comment by edavis** [comment]
Ah, okay. I thought you had it running on your local machine and were trying to enable external access. Being on a VPS already should make this easier.

That server that launches on 127.0.0.1:5000 is only meant for local development. It's not the recommended way to deploy an app like this.

I'd suggest looking into http://gunicorn.org/. You'll run a command like `gunicorn hnrss:app` which'll load the app and listen on 127.0.0.1:8000. Then you'll configure Apache to pass incoming requests from the outside world to 127.0.0.1:8000.

There are more moving pieces with this method, but it'll be pretty robust. Plus it's the standard way of launching Python web apps so there are a ton of online docs to help you out.

An alternative, _not recommended_ way is to change the line to something like `app.run(host='0.0.0.0', port=5000, debug=False)` which'll make the local development server listen on all available IP addresses. You'll then be able to connect via http://<YourIPAddress>:5000/newest.

Definitely read [the docs](http://flask.pocoo.org/docs/0.12/api/#flask.Flask.run) on this to make sure you understand why it isn't recommended for production use, though. But it can be useful as its a simpler setup than the gunicorn option.

Good luck!

**Comment by srissel** [comment]
Many thanks this great explanation, it sounds really promising! I'll have a try with it,

**Comment by srissel** [comment]
Again, many thanks!
During the last about 90 minutes I was able to install Gunicorn, configure apache to pass request to your Python application "hnrss" and habe it run automatically on boot.

Finally a nice way to integrate Hacker News into News Aggregetors (in my case Flipboard mobile app).
Perfect!

**Comment by edavis** [comment]
Awesome! Glad to hear everything worked out.
