### ISSUE TITLE
Link to comments in article description?

### ISSUE THREAD

**Issue by KurtPreston** [edavis/hnrss#4]
Love this service!  Until recently, I was using [this](http://ashleyw.co.uk/project/hacker-news-feeds) for HN RSS.  One thing I liked about those feeds was that the description just contained a link to the comment feed.  This worked well with my RSS reader: I could read the article from the link, view the comments from the description.

Would it be possible to add a flag to HNRSS allowing the description to instead link to the comments?

**Comment by edavis** [comment]
Hi Kurt — Yeah, this should be doable. Glad you're finding hnrss useful!

I've been meaning to make a few other updates, so I'll tackle this along with them.

**Comment by edavis** [comment]
Hi Kurt — I just pushed this live. Thanks again for the suggestion.

**Comment by KurtPreston** [comment]
This works great!  Thanks a bunch!
