### ISSUE TITLE
Possible GUID isPermalink=false option?

### ISSUE THREAD

**Issue by Zweihander42** [edavis/hnrss#5]
Hey, thanks for this service! 
Some feed readers which will opt to use the GUID of an item as the item's link (even if there is a link specified). I believe this is because the RSS 2.0 spec says that the isPermalink attribute of GUID is true by default (and overrides link even if it's specified - though that's a debated area from the few searches I've done). 

The feed reader in question is Thunderbird's built-in RSS reader-
Original bug which had them change this behavior: https://bugzilla.mozilla.org/show_bug.cgi?id=327378

Feedly also seems to use the GUID instead of the link and I believe Google Reader used to use it as well before it closed down (thought they may have changed the behavior just before they closed).

Would it be possible to either change the <guid> element to <guid isPermaLink="false"> or to add an option to append something to the URL so it changes it? 

Not at all a critical problem -- using ?link=comments gives you something not too far off but just thought I'd throw it out there -- thanks!

**Comment by edavis** [comment]
Interesting. The NYT produces a bad feed nine years ago and we're still living with the consequences :)

So right now Thunderbird and Feedly use the URL in `<guid>` instead the URL in `<link>`? And you'd like for an option to enable `isPermalink=false` on `<guid>` so they use `<link>` instead?

Out of curiosity, how does `?link=comments` fix it? That just just makes the values of `<link>` and `<guid>` equal.

I'm not opposed to making this change if it helps.

**Comment by Zweihander42** [comment]
Yup, that's exactly right. They're ignoring the `<link>` as they're assuming `<guid>` is set to true - if you add `isPermalink=false` to `<guid>`, they should use the `<link>` instead. 

You can see it in action on Thunderbird--

Using news.ycombinator.com/rss (which doesn't have a guid):
![image](https://cloud.githubusercontent.com/assets/1928813/7099265/d2685a38-dfbc-11e4-9598-07c14458516e.png)

Using hnrss:
![image](https://cloud.githubusercontent.com/assets/1928813/7099274/0858fde6-dfbd-11e4-94dd-0437b0e2b02a.png)


Using hnrss with `?link=comments`:
http://i.imgur.com/7W360LI.png
![image](https://cloud.githubusercontent.com/assets/1928813/7099277/160a2df2-dfbd-11e4-82cc-56fa149f3743.png)

`?link=comments` alleviates it by still keeping the direct link on the page. It only falls short for certain workflows such as using keyboard shortcuts to open an item's 'Website' link in Thunderbird (and possibly Feedly if they have a similar shortcuts).

In Feedly, the `?link=comments` feed with an item's "Visit Website" or title hovered over looks like:
![image](https://cloud.githubusercontent.com/assets/1928813/7099307/a0ebd3d0-dfbd-11e4-939d-2621941ea907.png)

Also for reference, here's what a link with 'isPermalink=false' set looks like in Thunderbird:
![image](https://cloud.githubusercontent.com/assets/1928813/7099333/2b1e1068-dfbe-11e4-80c3-0dfe00a9ba9d.png)

That's from http://blog.acolyer.org/feed/ which has a different `<guid>` than `<link>` (though both evaluate to the same address). 


Definitely not a critical bug but thanks for taking a looks at it!

**Comment by edavis** [comment]
Hey @Zweihander42 — Haven't forgot about ya! Just haven't had the time to dig into this yet.

Great examples, too. Very helpful. I hope to spend some time on this soon.

Thanks again.

**Comment by edavis** [comment]
@Zweihander42 — Not exactly the quickest turnaround, but this is now live :)

I went with setting `isPermaLink="false"` unconditionally because I think it just makes more sense than making it optional.

If RSS feeds hosted on Wordpress.com set that attribute unconditionally, we're probably in the clear. I'm sure they thoroughly researched the pros/cons and decided it was worth it.

Let me know if this clears up your Thunderbird issue.

Have a great day!

**Comment by Zweihander42** [comment]
@edavis -- Works as expected!

Thunderbird and Feedly both look good:
![image](https://cloud.githubusercontent.com/assets/1928813/7993413/03978452-0ad4-11e5-8471-295c64fb8435.png)

and with title hovered over:
![image](https://cloud.githubusercontent.com/assets/1928813/7993499/7823ca7e-0ad4-11e5-9763-8b2fd36b1689.png)


Thanks so much, appreciate it!

**Comment by edavis** [comment]
Happy to help!
