### ISSUE TITLE
Obsolete date format

### ISSUE THREAD

**Issue by onur** [edavis/hnrss#6]
hnrss is using obsolete time zone syntax. GMT is defined obsolete in rfc2822. So this format: `Tue, 07 Jul 2015 11:37:52 GMT` is obsolete and some parsers (such as `strptime(3)` in libc) failing to parse this format.

Please use `+0000` instead of `GMT` in `rss.py:77`

**Comment by edavis** [comment]
I've updated the timezone string to return "+0000" instead of "GMT."

Thanks!
